### ISSUE TITLE
ll_categorical_objective tends to saturate very quickly

### ISSUE THREAD

**Issue by coventry** [JonathanRaiman/infogan#1]
Any idea why this might be happening?  It doesn't with the openai version.  For example:

![evolution_of_categorical_objective](https://cloud.githubusercontent.com/assets/70152/19289876/d38d80e4-8fda-11e6-8eb3-cf0859c835ca.png)

**Comment by JonathanRaiman** [comment]
I'm not sure. I imagine this has something to do with weighing the objectives differently, or perhaps reducing the expressive power of the discriminator a bit. Have you found a good explanation?

**Comment by coventry** [comment]
No, not yet.

**Comment by JonathanRaiman** [comment]
Ok. I would be curious to know if you find out :)
